select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
PRODUCT_ID, USER_ID, sum(SALES_AMOUNT) as SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE between "2022-03-01" and "2022-03-31"
group by SALES_DATE, PRODUCT_ID, USER_ID

union all

select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, 
PRODUCT_ID, NULL AS USER_ID, sum(SALES_AMOUNT) as SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE between "2022-03-01" and "2022-03-31"
group by SALES_DATE, PRODUCT_ID
order by SALES_DATE, PRODUCT_ID, USER_ID;