SELECT ID, CASE WHEN ROUND(SIZE_RANK * 100, 2) <= 25 THEN 'CRITICAL'
                WHEN ROUND(SIZE_RANK * 100, 2) <= 50 THEN 'HIGH'
                WHEN ROUND(SIZE_RANK * 100, 2) <= 75 THEN 'MEDIUM'
                ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
FROM ECOLI_DATA) AS TMP
ORDER BY ID;