SELECT DISTINCT(CAR_ID), (
CASE WHEN EXISTS (
    SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS sub
    WHERE sub.CAR_ID = main.CAR_ID 
    AND "2022-10-16" BETWEEN START_DATE AND END_DATE) THEN "대여중"
    ELSE "대여 가능" END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS main
ORDER BY CAR_ID DESC;