SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d
JOIN SKILLCODES s 
  ON d.SKILL_CODE & s.CODE = s.CODE
WHERE s.CATEGORY = 'Front End'
GROUP BY d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
ORDER BY d.ID;