SELECT a.YEAR AS YEAR, b.MAX_SIZE - a.SIZE_OF_COLONY AS YEAR_DEV, a.ID AS ID
FROM (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR 
    FROM ECOLI_DATA
) AS a
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE 
    FROM ECOLI_DATA 
    GROUP BY YEAR
) AS b
ON a.YEAR = b.YEAR ORDER BY YEAR, YEAR_DEV;