SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE FROM (
    SELECT FISH_TYPE, AVG(COALESCE(LENGTH, 10)) AS AVG_LENGTH, 
    MAX(LENGTH) AS MAX_LENGTH, COUNT(*) AS FISH_COUNT 
    FROM FISH_INFO GROUP BY FISH_TYPE) AS a
    WHERE AVG_LENGTH >= 33 ORDER BY FISH_TYPE;